<div class="container">
  <h1>Nouvelle newsletter <?= $issue;?></h1>
	<div class="row">
  	<form role="form" action="<?= $this->url('/create/newsletter/:issue',array('issue'=>$issue)); ?>" method="POST">
  		<?php foreach ($sections as $array => $section):?>
  	  <label><h3><?= $section?></h3></label>
  	    <div class="multi-field-wrapper">
  	      <div class="multi-fields entry input-group col-xs-9">
  	        <div class="multi-field form-group input-group">
  	          <input type="text" name="<?=$section?>[]" class="form-control"/>
  						<span class="input-group-btn">
  		          <button type="button" class="remove-field btn btn-danger btn-remove">
  									<span class="glyphicon glyphicon-minus"></span>
  							</button>
  					</span>
  	        </div>
  	      </div>
  				<div class="input_fields_wrap">
  	    <button type="button" class="add-field btn btn-success btn-add"> <span class="glyphicon glyphicon-plus"></span> Ajouter un champ</button>
  		</div>
  	  </div>
  		<?php endforeach ?>
  		<div class="form-group">
        <div class="col-xs-offset-8 col-xs-2">
          <button type="submit" class="btn btn-primary btn-block btn-lg">Créer</button>
        </div>
      </div>
  </form>
	</div>
</div>
