<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff;">
  <tr>
    <td>
      <!-- ARTICLE-->
	      <table class="row">
        <tr>
          <td class="wrapper last">
            <table class="twelve columns">
              <tr>
                <td class="text-pad">
                  <h6 class="dento"><?= $title ?></h6>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <table class="row">
        <tr>
          <td class="wrapper">
            <table class="six columns">
              <tr>
                <td class="text-pad">
                  <img src="<?= $img ?>" width="250" height="125"/>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
          <td class="wrapper last">
            <table class="six columns">
              <tr>
                <td class="text-pad">
                  <p><?= $text ?></p>
                </td>
                <td class="expander"></td>
              </tr>
			        <tr>
                <td class="text-pad">
                  <table class="button round dento">
                    <tr>
                      <td> 
                          <a href="<?= $this->analytics(Atomik::url($link),$section,$count)?>"><?= Atomik\Translations::translate('Lire l\'article')?></a>
                      </td>
                    </tr>
                  </table>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <!--/ARTICLE-->
    </td>
  </tr>
</table>