<table class="container block" style="background-color:#ffffff;" bgcolor="#ffffff">
  <tbody>
    <tr>
      <td>
        <table class="row">
          <tbody>
            <tr>
              <td class="wrapper">
                <table class="six columns">
                  <tbody>
                    <tr>
                      <td class="center">
                       <center>
                         <h6 class="dento">Devenez des spécialistes, au-delà de votre spécialité</h6>
                       </center>
                     </td>
                   </tr>
                   <tr>
                    <td class="center">
                      <center>
                        <a href="http://www.librairie-garanciere.com/applications-chirurgicales-ultrasons.htm"><img class="center" src="http://www.librairie-garanciere.com/content/product_1433358b.gif" height="252" width="180"></a>			
                      </center>
                    </td>
                    <td class="expander"></td>
                  </tr>
                  <tr>
                    <td>
                      <table class="button">
                        <tbody>
                          <tr>
                            <td>
                              <a href="http://www.librairie-garanciere.com/devenez-specialistes-au-dela-votre-specialite-vient-paraitre.htm">J'achète</a>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="wrapper last">
             <table class="six columns">
              <tbody>
                <tr>
                  <td class="center">
                   <center>
                     <h6 class="dento">Devenez des spécialistes, au-delà de votre spécialité</h6>
                   </center>
                 </td>
               </tr>
               <tr>
                <td class="center">
                 <center>
                  <a href="http://www.librairie-garanciere.com/codes-la-relation-dentiste-patient.htm"><img class="center" src="http://www.librairie-garanciere.com/content/product_7654628hd.jpg" height="252" width="180"></a>					
                </center>
              </td>
              <td class="expander"></td>
            </tr>
            <tr>
              <td>
                <table class="button">
                  <tbody>
                    <tr>
                      <td>
                        <a href="http://www.librairie-garanciere.com/l-oreille-numerique.htm">J'achète</a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
      </td>
      <td class="expander"></td>
    </tr>
  </tbody>
</table>
<table class="row">
  <td class="wrapper last offset-by-three">
    <table class="six columns">
      <tbody>
        <tr>
          <td>
            <table class="button">
              <tbody>
                <tr>
                  <td>
                    <a href="http://www.librairie-garanciere.com/">Toute la librairie</a>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
  </td>
  <td class="expander"></td>
</table>
</td>
</tr>
</tbody>
</table>
