<table class="container" bgcolor="#ffffff" style="background-color:#ffffff">
  <tr>
    <td>
      <!-- BREVE-->
      <table class="row">
        <tr>
          <td class="wrapper last">
            <table class="twelve columns">
              <tr>
                <td class="text-pad">
                  <h5><?= $title ?></h5>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <table class="row">
        <tr>
          <td class="wrapper last">
            <table class="twelve columns">
              <tr>
                <td class="text-pad">
                  <p><?= $text ?></p>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <table class="row">
        <tr>
          <td class="wrapper  offset-by-nine last">
            <table class="three columns">
              <tr>
                <td class="text-pad">
                  <table class="button">
                    <tr>
                      <td>
                        <a href="<?= Atomik::url($link)?>">Lire la suite</a>
                      </td>
                    </tr>
                  </table>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <!-- /BREVE-->
    </td>
  </tr>
</table>
