<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff">
  <tr>
    <td>
      <!--SECTIONS-->
				<table class="button">
					<tr>
						<td class="wrapper last" style="background-color:#961325!important;" bgcolor="#961325">
							<table class="twelve columns">
								<tr>
									<td class="center" style="background-color:#961325!important;border:none;" bgcolor="#961325">
											<center>
											<a style="color:#ffffff;font-size:24px;font-weight:700;" href="http://annonces.edp-audio.fr/offre/ajout/etape-1">Déposez votre annonce</a>
											</center>
											</td>
								 	<td class="expander"></td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			<!--/SECTIONS-->
		</td>
	</tr>
</table>
