<table class="container" bgcolor="#E9E9E9" style="#E9E9E9">
	<tr>
		<td>
			<!--HEADER-->
			<table class="row" bgcolor="#E9E9E9" style="#E9E9E9">
				<tr>
					<td class="wrapper last">
						<table class="twelve columns">
							<tr>
								<td>
									<a href="http://annonces.edp-audio.fr/offre/ajout/etape-1"><img src="http://image.news.groupe-edp.fr/lib/fe8c1272776c0c7871/m/4/candidat-banniere.jpg" width="580" height="auto" style="width:580px;height:auto"/></a>
								</td>
								<td class="expander"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<!--/HEADER-->
		</td>
	</tr>
</table>
<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff">
	<tr>
		<td>
			<!--SECTIONS-->
			<table class="button">
				<tr>
					<td class="wrapper last" style="background-color:#961325!important; background:#961325!important" bgcolor="#961325">
						<table class="twelve columns">
							<tr>
								<td class="center" style="background-color:#961325!important;border:none; background:#961325!important" bgcolor="#961325">
									<center>
										<a style="color:#ffffff;font-size:24px;font-weight:700;" href="http://annonces.edp-audio.fr/offre/ajout/etape-1">Déposez votre annonce</a>
									</center>
								</td>
								<td class="expander"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<!--/SECTIONS-->
		</td>
	</tr>
</table>
