<table class="container block" style="background-color:#ffffff;" bgcolor="#ffffff">
      <tbody><tr>
        <td>
          <table class="row">
            <tbody><tr>
              <td class="wrapper">
                <table class="four columns">
                  <tbody><tr>
                    <td class="center">
					<center>
						 <a href="http://www.librairie-garanciere.com/devenez-specialistes-au-dela-votre-specialite-vient-paraitre.htm"><img class="center" src="http://www.edp-audio.fr/images/newsletter/divers/devenez-des-specialistes.jpg" height="252" width="180"></a>					
					</center>
					
					</td>
                 		<td class="expander"></td>
                  </tr>
				  <tr>
                    <td>
	
						<table class="button">
                            <tbody><tr>
                              <td>
                                <a href="http://www.librairie-garanciere.com/devenez-specialistes-au-dela-votre-specialite-vient-paraitre.htm">Acheter</a>
                              </td>
                            </tr>
                          </tbody></table>

					
					</td>
                 
                  </tr>
                </tbody></table>
              </td>
	
			  <td class="wrapper">
                <table class="four columns">
                  <tbody><tr>
                    <td class="center">
					<center>
					<a href="http://www.librairie-garanciere.com/l-audition-guide-complet.htm">	<img class="center" src="http://www.edp-audio.fr/images/newsletter/divers/audition-guide-complet.jpg" height="252" width="180"></a>					
					</center>
					
					</td>
                 		<td class="expander"></td>
                  </tr>
				  <tr>
                    <td>
	
						<table class="button">
                            <tbody><tr>
                              <td>
                                <a href="http://www.librairie-garanciere.com/l-audition-guide-complet.htm">Acheter</a>
                              </td>
                            </tr>
                          </tbody></table>

					
					</td>
                 
                  </tr>
                </tbody></table>
              </td>
			
              <td class="wrapper last">
       <table class="four columns">
                  <tbody><tr>
                    <td class="center">
					<center>
						<a href="http://www.librairie-garanciere.com/l-oreille-numerique.htm"><img class="center" src="http://www.edp-audio.fr/images/newsletter/divers/oreille-numerique-edp.jpg" height="252" width="180"></a>					
					</center>
					
					</td>
                 		<td class="expander"></td>
                  </tr>
				  <tr>
                    <td>
	
						<table class="button">
                            <tbody><tr>
                              <td>
                                <a href="http://www.librairie-garanciere.com/l-oreille-numerique.htm">Acheter</a>
                              </td>
                            </tr>
                          </tbody></table>

					
					</td>
                 
                  </tr>
                </tbody></table>
              </td>
			  <td class="expander"></td>
            </tr>
          </tbody></table>
        </td>
      </tr>
    </tbody></table>
