<!-- PUB -->
<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff">
  <tr>
    <td>
      <table class="row" bgcolor="#ffffff" style="background-color:#ffffff">
        <tr>
          <td class="wrapper last">
            <table class="twelve columns">
              <tr>
                <td>
                  <a href="<?= Atomik::url($link) ?>"><img src="<?= $banner ?>" width="580" height="auto" style="width:580px;height:auto"/></a>
                </td>
                <td class="expander"></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<!-- FIN PUB -->
