  <table class="container block" bgcolor="#ffffff" style="background-color:#ffffff;">
      <tr>
        <td>
          <table class="row">
            <tr>
              <td class="wrapper">
                <table class="seven columns">
				  <tr>
                    <td class="left-text-pad">
                      <h6>Zoom sur…</h6><p>Le marché des compléments alimentaires (page 9)</p>
                    </td>
                    <td class="expander"></td>
                  </tr>
				   <tr>
                    <td class="left-text-pad">
                      <h6>Zoom sur…</h6><p>Le marché des compléments alimentaires (page 9)</p>
                    </td>
                    <td class="expander"></td>
                  </tr>
				  <tr>
                    <td class="left-text-pad">
                      <h6>Zoom sur…</h6><p>Le marché des compléments alimentaires (page 9)</p>
                    </td>
                    <td class="expander"></td>
                  </tr>
				   <tr>
                    <td class="left-text-pad">
                      <h6>Zoom sur…</h6><p>Le marché des compléments alimentaires (page 9)</p>
                    </td>
                    <td class="expander"></td>
                  </tr>
                </table>
              </td>
              <td class="wrapper last">
                <table class="four columns">
                  <tr>
                    <td class="panel">
						<center>
						<p style="text-align:center">Pour lire le n°114</p>
                      <img src="http://image.news.groupe-edp.fr/lib/fe8c1272776c0c7871/m/2/CouvPP113-Cliquez-ici.gif" width="216" height="282" alt="" class="center"/>
					  </center>
                    </td>
                    <td class="expander"></td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
