<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff">
  <tr>
    <td>
      <!--SECTIONS-->
				<table class="row " bgcolor="<?= $color ?>">
					<tr>
						<td class="wrapper last">
							<table class="twelve columns">
								<tr>
									<td class="left-text-pad">
											<p class="title"><?= mb_strtoupper(Atomik\Translations::translate($name),'UTF-8') ?></p>
									</td>
								 	<td class="expander"></td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			<!--/SECTIONS-->
		</td>
	</tr>
</table>
