<table class="container block" bgcolor="#ffffff" style="background-color:#ffffff">
     <tr>
      <td>
        <table class="row">
          <tr>
            <td class="wrapper">
              <table class="six columns">
                <tr>
                  <td class="six sub-columns">
																		<a href="<?= $banner1link ?>"><img src="<?= $banner1 ?>" width="135" height="auto" style="width:135px;height:auto;"/></a>
                  </td>
                  <td class="six sub-columns last">
																		<a href="<?= $banner2link ?>"><img src="<?= $banner2 ?>" width="135" height="auto" style="width:135px;height:auto;"/></a>
                  </td>
                  <td class="expander"></td>
                </tr>
              </table>
            </td>
            <td class="wrapper last">
              <table class="six columns">
                <tr>
                  <td class="six sub-columns">
																		<a href="<?= $banner3link ?>"><img src="<?= $banner3 ?>" width="135" height="auto" style="width:135px;height:auto;"/></a>
                  </td>
                  <td class="six sub-columns last">
																		<a href="<?= $banner4link ?>"><img src="<?= $banner4 ?>" width="135" height="auto" style="width:135px;height:auto;"/></a>
                  </td>
                  <td class="expander"></td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
