<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Atomik Skeleton Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="<?php echo $this->asset('assets/css/bootflat.css') ?>" rel="stylesheet">
    <link href="<?php echo $this->asset('assets/css/layout.css') ?>" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
  </head>
  <body style="background-color: rgb(241, 242, 246)">
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">Newsletter-maker Application</a>
          <ul class="nav">
            <li class="active"><a href="<?php echo Atomik::url('/') ?>">HOME</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <?php if (count($this['flash_messages'])): ?>
        <?php foreach ($this['flash_messages'] as $label => $messages): ?>
          <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?php echo $label ?>"><?php echo $message ?></li>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php endif ?>

      <div id="content">
        <?php echo $contentForLayout; ?>
      </div>
    </div>
    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>
      
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="<?php echo $this->asset('assets/js/fields.js') ?>"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?php echo $this->asset('assets/js/bootstrap.min.js') ?>"></script>
  </body>
</html>
